/*
  Honest Harvest - ethers.js Contract Connector

  Purpose:
  - Gives frontend/backend code a simple way to connect to the deployed smart contract.
  - Reads the ABI and deployed address from files generated by scripts/deploy.js.

  Expected generated files:
  - abi/SupplyChainContract.json
  - deployments/deployed-address.json

  Install:
  npm install ethers

  Local Hardhat node:
  npx hardhat node

  Deploy:
  npx hardhat run scripts/deploy.js --network localhost
*/

const { ethers } = require("ethers");

const contractAbi = require("../abi/SupplyChainContract.json");
const deployedContract = require("../deployments/deployed-address.json");

const LOCAL_RPC_URL = "http://127.0.0.1:8545";

/*
  Hardhat local test account #0 private key.

  IMPORTANT:
  This key is publicly known and only safe for local Hardhat testing.
  Never use this on a real testnet or mainnet.
*/
const LOCAL_PRIVATE_KEY =
  "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";

function getProvider(rpcUrl = LOCAL_RPC_URL) {
  return new ethers.JsonRpcProvider(rpcUrl);
}

function getSigner(rpcUrl = LOCAL_RPC_URL, privateKey = LOCAL_PRIVATE_KEY) {
  const provider = getProvider(rpcUrl);
  return new ethers.Wallet(privateKey, provider);
}

function getReadOnlyContract(rpcUrl = LOCAL_RPC_URL) {
  const provider = getProvider(rpcUrl);

  return new ethers.Contract(
    deployedContract.address,
    contractAbi,
    provider
  );
}

function getWritableContract(
  rpcUrl = LOCAL_RPC_URL,
  privateKey = LOCAL_PRIVATE_KEY
) {
  const signer = getSigner(rpcUrl, privateKey);

  return new ethers.Contract(
    deployedContract.address,
    contractAbi,
    signer
  );
}

/*
  Example usage:

  const contract = getWritableContract();

  const tx = await contract.registerItem(dataHash);
  await tx.wait();

  const owner = await contract.getItemOwner(1);
  console.log(owner);
*/

module.exports = {
  getProvider,
  getSigner,
  getReadOnlyContract,
  getWritableContract
};
